### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by robdecker** [arshad/drupal-template-helper#3]
When using the relatively new "dark" theme that came out in a recent Chrome build, the templates panel is difficult to read.

![screen shot 2016-04-05 at 4 06 45 pm](https://cloud.githubusercontent.com/assets/852280/14301106/e8b4cf0c-fb49-11e5-8a29-35d6cdecbb84.png)

**Comment by saschaeggi** [comment]
+1 :)

**Comment by arshad** [comment]
Thanks @robdecker. We'll fix it.

**Comment by arshad** [comment]
Added the option to enable the Dark theme. Tagging a new release soon. See screenshot below.

![drupal-template-helper](https://cloud.githubusercontent.com/assets/124599/14503284/7b8f9376-01c0-11e6-8ace-45822964a5d5.png)

**Comment by robdecker** [comment]
Looks great!

**Comment by danny-englander** [comment]
@arshad - The last release I see in the Chrome webstore is from April 5. I am guessing this fix has not made it to the plugin there yet? Thanks.

**Comment by arshad** [comment]
I'll tag a new release tomorrow.

**Comment by arshad** [comment]
New version released with fix. Please update. Closing this issue. Thanks everyone.
