### ISSUE TITLE
add setting to also display the source comments

### ISSUE THREAD

**Issue by saschaeggi** [arshad/drupal-template-helper#4]
It would be really nice if there would be a setting to also enable the source comments – as it looks as they are stripped out at the moment.

**Comment by arshad** [comment]
Agreed. We'll add the option.

**Comment by saschaeggi** [comment]
@arshad awesome :)

**Comment by arshad** [comment]
@saschaeggi Added the **Show HTML comments** option. Will tag a new release soon.

![drupal-html-helper-show-comments-option](https://cloud.githubusercontent.com/assets/124599/14439446/3cf9cc2e-003c-11e6-8c7a-ed58246a557f.png)

**Comment by saschaeggi** [comment]
@arshad wow that was fast, looking forward to the new version :)

**Comment by robdecker** [comment]
I've noticed that while the comments are hidden, they are still there and receive focus. Often I use the keyboard arrows to move focus up or down the DOM tree. It was confusing at first when moving to another element and the focus "disappeared".

**Comment by arshad** [comment]
New version released with fix. Please update. Closing this issue. Thanks everyone.
