### ISSUE TITLE
Doesn't work with Chrome Canary

### ISSUE THREAD

**Issue by cosmicdreams** [arshad/drupal-template-helper#5]
At the time of the creation of this issue, Chrome is at v49 and Chrome Canary is at v51.  I was able to see that this extension is working for v49 but not for v51 (Canary).

**Comment by anakinjay** [comment]
not working for me in chrome Version 49.0.2623.110 (64-bit) .  Went through the installation steps 3 times.

**Comment by arshad** [comment]
@cosmicdreams I've not tried with Canary yet. I'll write some tests and run it and see why it's not working. Thanks for the report :+1: 

@anakinjay Can you see the Templates panel or not seeing anything?

**Comment by MichelleCox** [comment]
I have Version 49.0.2623.112 (64-bit) and I can see it hiding the theme_debug comments but the "templates" tab comes back saying it couldn't find any.

**Comment by danny-englander** [comment]
I just got this working with Chrome Canary and a Drupal 7 site.  My version on Mac is: `51.0.2703.0 canary (64-bit)`. I'll see if I can get it working with a D8 site this weekend.

**Comment by tanc** [comment]
I'm on Chrome 50.0.2661.75 and I've followed the installation steps and enabled debugging on a D7 site. I can see the debug comments in the HTML on other browsers but not on Chrome. I can't see the "templates" tab in dev tools.
